# Generated by Django 5.1.3 on 2025-01-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0029_company_bill_leaf_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_bill',
            name='date',
            field=models.DateField(),
        ),
    ]
