# Generated by Django 5.1.3 on 2025-01-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0031_company_recived_payment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_recived_payment_transaction',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.company'),
        ),
    ]
