# Generated by Django 5.1.3 on 2025-01-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0032_company_recived_payment_transaction_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_recived_payment_transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
